project_name: nodereg
builds:
- binary: nodereg
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
dockers:
- image: rossedman/nodereg
git:
  short_hash: true
release:
  github:
    owner: rossedman
    name: nodereg
  draft: true
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}"